package entity;
// Generated Mar 26, 2019 3:07:53 PM by Hibernate Tools 4.3.1



/**
 * Web111 generated by hbm2java
 */
public class Web111  implements java.io.Serializable {


     private Integer id;
     private String firstname;
     private String lastname;
     private String email;
     private String password;
     private String contact;
     private String gender;
     private String doB;

    public Web111() {
    }

    public Web111(String firstname, String lastname, String email, String password, String contact, String gender, String doB) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.password = password;
       this.contact = contact;
       this.gender = gender;
       this.doB = doB;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDoB() {
        return this.doB;
    }
    
    public void setDoB(String doB) {
        this.doB = doB;
    }




}


